"""
Converts recipes.json -> addon/CraftCalc/Data.lua
Run once from the project root: python gen_data_lua.py
"""
import json, os

with open("recipes.json", "r", encoding="utf-8") as f:
    data = json.load(f)

os.makedirs("addon/CraftCalc", exist_ok=True)

lines = []
lines.append("-- Auto-generated by gen_data_lua.py. Do not edit manually.\n\n")

# ── Recipe data ──────────────────────────────────────────────────────────────
lines.append("CC_RECIPES = {\n")
for prof_key, prof in data["professions"].items():
    lines.append(f'  ["{prof_key}"] = {{\n')
    lines.append(f'    name = "{prof["name"]}",\n')
    lines.append("    recipes = {\n")
    for r in prof["recipes"]:
        name = r["name"].replace("\\", "\\\\").replace('"', '\\"')
        result = r.get("resultId") or "nil"
        skill = r.get("skillReq") or 1
        reagents = ",".join(f'{{{rr["itemId"]},{rr["qty"]}}}' for rr in r["reagents"])
        lines.append(
            f'      {{id={r["spellId"]},result={result},skill={skill},'
            f'name="{name}",r={{{reagents}}}}},\n'
        )
    lines.append("    },\n")
    lines.append("  },\n")
lines.append("}\n\n")

# ── Item name lookup ─────────────────────────────────────────────────────────
lines.append("CC_ITEMS = {\n")
for item_id, item in data["items"].items():
    name = item["name"].replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'  [{item_id}]="{name}",\n')
lines.append("}\n")

out = "addon/CraftCalc/Data.lua"
with open(out, "w", encoding="utf-8") as f:
    f.writelines(lines)

recipe_count = sum(len(p["recipes"]) for p in data["professions"].values())
print(f"Generated {out}")
print(f"  {len(data['professions'])} professions, {recipe_count} recipes, {len(data['items'])} items")
